import { css, rawCssString } from "hono/css";
import { scopes } from "./scopes.ts";

const iconRules = [
  ["github", [
    '[href*="github.blog"]',
    '[href*="github.com"]',
    '[href*="githubusercontent.com"]',
  ]],
  ["gitlab", ['[href*="gitlab.com"]']],
  ["wikipedia", ['[href*="wikipedia.org"]']],
  ["apple", ['[href*="apple.com"]', '[href*="support.apple.com"]']],
  ["appstore", ['[href*="apps.apple.com"]']],
  ["applemusic", [
    '[href*="js-cdn.music.apple.com"]',
    '[href*="music.apple.com"]',
  ]],
  ["google", [
    '[href*="about.google"]',
    '[href*="blog.google"]',
    '[href*="google.com/search"]',
    '[href*="googleblog.com"]',
  ]],
  ["youtube", ['[href*="youtu.be"]', '[href*="youtube.com"]']],
  ["googlechrome", [
    '[href*="chrome.google"]',
    '[href*="chromium.org"]',
    '[href*="developer.chrome.com"]',
    '[href*="web.dev"]',
  ]],
  ["googledrive", ['[href*="drive.google"]']],
  ["googledocs", ['[href*="docs.google.com"]']],
  ["googlecolab", ['[href*="colab.research.google"]']],
  ["googlefonts", ['[href*="fonts.google"]']],
  ["x", ['[href*="twitter.com"]', '[href*="x.com"]']],
  ["linkedin", ['[href*="linkedin.com"]']],
  ["facebook", ['[href*="facebook.com"]']],
  ["instagram", ['[href*="instagram.com"]']],
  ["threads", ['[href*="threads.net"]']],
  ["mastodon", ["[href*=mastodon]", "[href*=social\\.silicon\\.moe]"]],
  ["reddit", ['[href*="reddit.com"]']],
  ["ycombinator", ['[href*="news.ycombinator.com"]']],
  ["discord", ['[href*="discord.com"]', '[href*="discord.gg"]']],
  ["slack", ['[href*="slack.com"]']],
  ["stackoverflow", [
    '[href*="stackexchange.com"]',
    '[href*="stackoverflow.com"]',
  ]],
  ["mdnwebdocs", ['[href*="developer.mozilla.org"]', '[href*="mdn.io"]']],
  ["npm", ['[href*="npm.im"]', '[href*="npmjs.com"]']],
  ["pypi", ['[href*="pypi.org"]']],
  ["rust", ['[href*="crates.io"]', '[href*="rust-lang.org"]']],
  ["codepen", ['[href*="codepen.io"]']],
  ["codesandbox", ['[href*="codesandbox.io"]']],
  ["jsfiddle", ['[href*="jsfiddle.net"]']],
  ["glitch", ['[href*="glitch.com"]']],
  ["replit", ['[href*="replit.com"]']],
  ["medium", ['[href*="medium.com"]']],
  ["devdotto", ['[href*="dev.to"]']],
  ["hashnode", ['[href*="hashnode.com"]', '[href*="hashnode.dev"]']],
  ["substack", ['[href*="substack.com"]']],
  ["ghost", ['[href*="ghost.io"]', '[href*="ghost.org"]']],
  ["notion", ['[href*="notion.site"]', '[href*="notion.so"]']],
  ["figma", ['[href*="figma.com"]']],
  ["framer", ['[href*="framer.com"]']],
  ["canva", ['[href*="canva.com"]']],
  ["miro", ['[href*="miro.com"]']],
  ["linear", ['[href*="linear.app"]']],
  ["trello", ['[href*="trello.com"]']],
  ["asana", ['[href*="asana.com"]']],
  ["atlassian", ['[href*="atlassian.com"]', '[href*="jira.com"]']],
  ["obsidian", ['[href*="obsidian.md"]']],
  ["logseq", ['[href*="logseq.com"]']],
  ["roamresearch", ['[href*="roamresearch.com"]']],
  ["vercel", ['[href*="vercel.app"]', '[href*="vercel.com"]']],
  ["netlify", ['[href*="netlify.app"]', '[href*="netlify.com"]']],
  ["cloudflare", ['[href*="cloudflare.com"]']],
  ["amazonaws", ['[href*="aws.amazon.com"]']],
  ["microsoftazure", ['[href*="azure.microsoft.com"]']],
  ["googlecloud", ['[href*="cloud.google"]']],
  ["heroku", ['[href*="heroku.com"]']],
  ["railway", ['[href*="railway.app"]']],
  ["render", ['[href*="render.com"]']],
  ["flydotio", ['[href*="fly.io"]']],
  ["supabase", ['[href*="supabase.com"]', '[href*="supabase.io"]']],
  ["planetscale", ['[href*="planetscale.com"]']],
  ["microsoft", ['[href*="microsoft.com"]']],
  ["amazon", ['[href*="amazon.com"]']],
  ["netflix", ['[href*="netflix.com"]']],
  ["spotify", ['[href*="developer.spotify.com"]', '[href*="spotify.com"]']],
  ["spacex", ['[href*="starlink.com"]']],
  ["tesla", ['[href*="tesla.com"]']],
  ["openai", ['[href*="openai.com"]']],
  ["anthropic", ['[href*="anthropic.com"]']],
  ["huggingface", ['[href*="huggingface.co"]']],
  ["react", ['[href*="react.dev"]', '[href*="reactjs.org"]']],
  ["nextdotjs", ['[href*="nextjs.org"]']],
  ["vuedotjs", ['[href*="vuejs.org"]']],
  ["svelte", ['[href*="svelte.dev"]']],
  ["angular", ['[href*="angular.io"]']],
  ["astro", ['[href*="astro.build"]']],
  ["solid", ['[href*="solidjs.com"]']],
  ["tailwindcss", ['[href*="tailwindcss.com"]']],
  ["nodedotjs", ['[href*="nodejs.org"]']],
  ["deno", ['[href*="deno.com"]', '[href*="deno.land"]']],
  ["bun", ['[href*="bun.sh"]']],
  ["typescript", ['[href*="typescriptlang.org"]']],
  ["go", ['[href*="go.dev"]', '[href*="golang.org"]']],
  ["python", ['[href*="python.org"]']],
  ["webpack", ['[href*="webpack.js.org"]']],
  ["vite", ['[href*="vitejs.dev"]']],
  ["esbuild", ['[href*="esbuild.github.io"]']],
  ["turborepo", ['[href*="turbo.build"]']],
  ["graphql", ['[href*="graphql.org"]']],
  ["docker", ['[href*="docker.com"]']],
  ["kubernetes", ['[href*="kubernetes.io"]']],
  ["naver", ['[href*="naver.com"]']],
  ["kakao", ['[href*="kakao.com"]', '[href*="kakaocorp.com"]']],
  ["velog", ['[href*="velog.io"]']],
  ["tistory", ['[href*="tistory.com"]']],
  ["slideshare", ['[href*="slideshare.net"]']],
  ["speakerdeck", ['[href*="speakerdeck.com"]']],
  ["producthunt", ['[href*="producthunt.com"]']],
  ["dribbble", ['[href*="dribbble.com"]']],
  ["behance", ['[href*="behance.net"]']],
  ["arxiv", ['[href*="arxiv.org"]']],
  ["w3c", ['[href*="w3.org"]']],
  ["internetarchive", ['[href*="archive.org"]']],
  ["perplexity", ['[href*="perplexity.ai"]']],
  ["kaggle", ['[href*="kaggle.com"]']],
  ["weightsandbiases", ['[href*="wandb.ai"]']],
  ["replicate", ['[href*="replicate.com"]']],
  ["googlegemini", ['[href*="ai.google"]', '[href*="gemini.google.com"]']],
  ["bitbucket", ['[href*="bitbucket.org"]']],
  ["visualstudiocode", ['[href*="code.visualstudio.com"]']],
  ["jetbrains", ['[href*="jetbrains.com"]']],
  ["cursor", ['[href*="cursor.com"]', '[href*="cursor.sh"]']],
  ["zedindustries", ['[href*="zed.dev"]']],
  ["homebrew", ['[href*="brew.sh"]']],
  ["firebase", ['[href*="firebase.google.com"]']],
  ["googleplay", ['[href*="play.google.com"]']],
  ["googlemaps", ['[href*="maps.google"]']],
  ["googlescholar", ['[href*="scholar.google"]']],
  ["googleanalytics", ['[href*="analytics.google"]']],
  ["mongodb", ['[href*="mongodb.com"]']],
  ["postgresql", ['[href*="postgresql.org"]']],
  ["redis", ['[href*="redis.io"]']],
  ["elastic", ['[href*="elastic.co"]']],
  ["nginx", ['[href*="nginx.com"]', '[href*="nginx.org"]']],
  ["jest", ['[href*="jestjs.io"]']],
  ["playwright", ['[href*="playwright.dev"]']],
  ["cypress", ['[href*="cypress.io"]']],
  ["remix", ['[href*="remix.run"]']],
  ["nuxtdotjs", ['[href*="nuxt.com"]']],
  ["flutter", ['[href*="flutter.dev"]']],
  ["dart", ['[href*="dart.dev"]']],
  ["swift", ['[href*="swift.org"]']],
  ["kotlin", ['[href*="kotlinlang.org"]']],
  ["ruby", ['[href*="ruby-lang.org"]']],
  ["prisma", ['[href*="prisma.io"]']],
  ["drizzle", ['[href*="drizzle.team"]', '[href*="orm.drizzle.team"]']],
  ["telegram", ['[href*="t.me"]', '[href*="telegram.org"]']],
  ["whatsapp", ['[href*="whatsapp.com"]']],
  ["zoom", ['[href*="zoom.us"]']],
  ["signal", ['[href*="signal.org"]']],
  ["bluesky", ['[href*="bsky.app"]', '[href*="bsky.social"]']],
  ["tiktok", ['[href*="tiktok.com"]']],
  ["twitch", ['[href*="twitch.tv"]']],
  ["pinterest", ['[href*="pinterest.com"]']],
  ["readthedocs", ['[href*="readthedocs.io"]', '[href*="readthedocs.org"]']],
  ["gitbook", ['[href*="gitbook.io"]']],
  ["docusaurus", ['[href*="docusaurus.io"]']],
  ["stripe", ['[href*="stripe.com"]']],
  ["paypal", ['[href*="paypal.com"]']],
  ["gumroad", ['[href*="gumroad.com"]']],
  ["circleci", ['[href*="circleci.com"]']],
  ["travisci", ['[href*="travis-ci.com"]', '[href*="travis-ci.org"]']],
  ["adobe", ['[href*="adobe.com"]']],
  ["sketch", ['[href*="sketch.com"]']],
  ["steam", ['[href*="steampowered.com"]', '[href*="store.steampowered.com"]']],
  ["unity", ['[href*="unity.com"]']],
  ["unrealengine", ['[href*="unrealengine.com"]']],
  ["techcrunch", ['[href*="techcrunch.com"]']],
  ["arstechnica", ['[href*="arstechnica.com"]']],
  ["hackernoon", ['[href*="hackernoon.com"]']],
  ["newyorktimes", ['[href*="nytimes.com"]']],
  ["thewashingtonpost", ['[href*="washingtonpost.com"]']],
  ["bbc", ['[href*="bbc.co.uk"]', '[href*="bbc.com"]']],
  ["cnn", ['[href*="cnn.com"]']],
  ["theguardian", ['[href*="theguardian.com"]']],
  ["axios", ['[href*="axios.com"]']],
  ["engadget", ['[href*="engadget.com"]']],
  ["buzzfeed", ['[href*="buzzfeed.com"]']],
  ["vox", ['[href*="vox.com"]']],
  ["digg", ['[href*="digg.com"]']],
  ["applenews", ['[href*="news.apple.com"]']],
  ["googlenews", ['[href*="news.google.com"]']],
  ["pocket", ['[href*="getpocket.com"]', '[href*="pocket.com"]']],
  ["flipboard", ['[href*="flipboard.com"]']],
  ["feedly", ['[href*="feedly.com"]']],
  ["inoreader", ['[href*="inoreader.com"]']],
  ["mailchimp", ['[href*="mailchimp.com"]']],
  ["kit", ['[href*="convertkit.com"]', '[href*="kit.com"]']],
  ["brevo", ['[href*="brevo.com"]', '[href*="sendinblue.com"]']],
  ["campaignmonitor", ['[href*="campaignmonitor.com"]']],
  ["hubspot", ['[href*="hubspot.com"]']],
  ["mailgun", ['[href*="mailgun.com"]']],
  ["mailtrap", ['[href*="mailtrap.io"]']],
  ["rss", [
    '[href$=".rss"]',
    '[href$="/feed"]',
    '[href$="/rss"]',
    '[href*="/atom.xml"]',
    '[href*="/feed.xml"]',
    '[href*="/rss.xml"]',
  ]],
  ["yarn", ['[href*="yarnpkg.com"]']],
  ["acm", ['[href*="dl.acm.org"]']],
  ["opentelemetry", ['[href*="opentelemetry.io"]']],
  ["elsevier", ['[href*="sciencedirect.com"]']],
] as const satisfies readonly (readonly [
  icon: string,
  hrefSelectors: readonly string[],
])[];

const iconRulesCss = iconRules.map(([icon, hrefSelectors]) =>
  String.raw`
    ${
    hrefSelectors.map((selector) =>
      `${scopes.document.root} a${selector}::before`
    ).join(",")
  } {
      content: "\00a0";
      mask-image: url("https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${icon}.svg");
    }
  `
).join("\n");

export const externalLinkIcons = css`${rawCssString(iconRulesCss)}`;
